### PR TITLE
[14.0][MIG] account_wallet_no_negative

### PR DESCRIPTION
**Pull request by rousseldenis**
Moved pos_account_wallet_no_negative to project specific as too much changes in Odoo necessary.

### CODE REVIEW

**Review by xavier-bouquiaux — APPROVED** [review]
LGTM

**Comment by rousseldenis** [comment]
@sbidoul

**Comment by sbidoul** [comment]
Why is this in a separate module ?

/ocabot merge patch

**Comment by sbidoul** [comment]
Go home bot, you are drunk.

**Pull request merged**
