### PR TITLE
[RFC] use the classic way to '_inheritS' from 'mail.alias'

### PR DESCRIPTION
**Pull request by Olivier-LAURENT**
[FIX] allow to no more create the alias from a function field (that launched an infinite recursion on the orm and crashed all tests in acsone-addons)

### CODE REVIEW

**Comment by Cedric-Pigeon** [comment]
:+1:  (Code review)

**Comment by JonathanNEMRY** [comment]
:+1: great improvement!

**Comment by laetitia-gangloff** [comment]
:+1:

**Comment by adrienpeiffer** [comment]
3 approvals. So, I merge

**Pull request merged**
