### PR TITLE
[8.0] new module to manage tiered pricing through odoo pricelist

### PR DESCRIPTION
**Pull request by Cedric-Pigeon**

### CODE REVIEW

**Comment by Cedric-Pigeon** [comment]
This pull request is linked to PR #4900 on Odoo.

**Comment by lukebranch** [comment]
@Cedric-Pigeon ,

Thanks.

**Comment by Cedric-Pigeon** [comment]
@lukebranch  For the moment I only improved the behavior of odoo pricelists.

**Comment by lukebranch** [comment]
@Cedric-Pigeon ,

Thanks for the explanation. I may work on a website_sale view for the view I want on the front page for my own projects in the meantime. Thanks for your work, i'll be implementing it into my dev install to test it out shortly.

**Comment by sbidoul** [comment]
@Cedric-Pigeon can you check why it is travis red?

Since this module seems to generate interest, do you think it's ready for OCA?

**Comment by Cedric-Pigeon** [comment]
@sbidoul It is red because the module depends on PR #4900 on Odoo.
This PR reorganizes the code of pricelist to allow override.

**Comment by sbidoul** [comment]
Here is the Odoo PR: https://github.com/odoo/odoo/pull/4900

**Comment by sbidoul** [comment]
Closing old stuff.

**Pull request closed without merging**
