### PR TITLE
remove hr_timesheet_no_closed_project_tasks

### PR DESCRIPTION
**Pull request by sbidoul**
Superseded by https://github.com/OCA/hr-timesheet/pull/70

cc/ @adrienpeiffer @lmignon @Olivier-LAURENT @JonathanNEMRY

### CODE REVIEW

**Comment by adrienpeiffer** [comment]
once merged in oca :+1:

**Comment by sbidoul** [comment]
@adrienpeiffer why wait to remove this one from acsone-addons?

**Comment by adrienpeiffer** [comment]
In the case of a transfer of module, I prefer to wait that the module is merged in OCA side bedore remove it from the other side. But it's just a matter of taste. So, this one can be merged

**Comment by sbidoul** [comment]
OCA/hr-timesheet#70, I therefore merge this one.

**Pull request merged**
