### PR TITLE
8.0 mass mailing distribution list mail forwarding

### PR DESCRIPTION
**Pull request by JonathanNEMRY**
Use the alias mechanism with the power of distribution list for mail forwarding integration

### CODE REVIEW

**Comment by JonathanNEMRY** [comment]
now rebased for travis :+1:

**Comment by Olivier-LAURENT** [comment]
:+1:

**Comment by lmignon** [comment]
Plz update the addons description to describe this new functionnality

**Comment by sbidoul** [comment]
Why is this PR moving files of other modules TO unported?

:-1: until this is clarified

**Comment by JonathanNEMRY** [comment]
@Olivier-LAURENT  tks for your work!! seems ok for me :+1:

**Comment by lmignon** [comment]
:+1:  
@sbidoul the files moved to unported have disappeared from the current PR when it has been rebased.

**Pull request merged**
