### PR TITLE
[readonly_bypass][IMP] apply this features for one2many fields by

### PR DESCRIPTION
**Pull request by JonathanNEMRY**
implemented bypass behavior into the bufferedDataSet

### CODE REVIEW

**Comment by JonathanNEMRY** [comment]
Any news about this PR?

**Comment by lmignon** [comment]
:+1:  Code review no tests

**Comment by Olivier-LAURENT** [comment]
:+1:

**Comment by lmignon** [comment]
I merge even if the modifications to travis.yml needs to be investigated.

**Pull request merged**
