### PR TITLE
[14.0][MIG] account_accountant_revert_menu

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Review by flotho — APPROVED** [review]
code review, LGTM, not able to test becaus no enterprise access.
Regards

**Comment by sbidoul** [comment]
BTW, I kind of remember @mart-e shared an interesting trick to make it possible to create accounting menu entries without depending on `account_accountant`. Can't find it right now but I remember it would make this module unnesessary.

**Comment by sbidoul** [comment]
BBTW @rousseldenis we really need to repair the 14.0 branch of this repo....

**Comment by sbidoul** [comment]
Ah, I found the trick: https://github.com/OCA/l10n-spain/pull/2094#issuecomment-1030125850

**Comment by sbidoul** [comment]
I updated the readme of this module to explain the alternative: https://github.com/acsone/acsone-addons/commit/f850f122b5c96166feb7d264e735205688ca5c7f

**Pull request merged**
