### PR TITLE
[8.0] Add resource calendar half day module

### PR DESCRIPTION
**Pull request by adrienpeiffer**

### CODE REVIEW

**Comment by JonathanNEMRY** [comment]
:+1:

**Comment by adrienpeiffer** [comment]
This one run fine in production for 6 month.
@acsone/acsone-odoo-team No remark ?

**Review by JonathanNEMRY — APPROVED** [review]

**Comment by JonathanNEMRY** [comment]
just the lint error to fix...otherwise it can be merge

**Review by Cedric-Pigeon — APPROVED** [review]

**Comment by adrienpeiffer** [comment]
The flake8 error is fixed in upstream

**Pull request merged**
